[build]
builder = "nixpacks"
buildCommand = "npm run build"
watchPatterns = ["frontend/**"]

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "frontend"
rootDirectory = "/frontend"